### ISSUE TITLE
Update Learn More CTA Button

### ISSUE THREAD

**Issue by kcbreuil** [bckrm/silverado#20]
@asasmith on the homepage, the LEARN MORE cta button doesn't do anything. Is this meant to trigger a scroll or link to another page?

**Comment by asasmith** [comment]
Need to confirm with either Josh or Emily where the CTA's should link to.

**Comment by asasmith** [comment]
@kcbreuil these links should be dynamic (the client will need to customize/update them via the cms). 

* Update so the the component accepts a prop for the link
* PropType should be string
* PropType is required

**Comment by kcbreuil** [comment]
@asasmith I think you already did this during dev 

CtaLink.propTypes = {
    cta: PropTypes.shape({
        link: PropTypes.string.isRequired,
        text: PropTypes.string.isRequired,
    }).isRequired,
};

isn't this what you are requesting?

**Comment by asasmith** [comment]
yep, didn't realize that was done already.
