### ISSUE TITLE
Ideas Page - Bulleted List 

### ISSUE THREAD

**Issue by kcbreuil** [bckrm/silverado#21]
@asasmith I know you have mentioned this being incomplete, but this section feels misaligned in comparison to other elements on the page.

**Comment by asasmith** [comment]
Definitely need design to weigh in more on this component

**Comment by kcbreuil** [comment]
@asasmith Should I follow up with Josh on this?

**Comment by asasmith** [comment]
@kcbreuil  please do. Thanks!

**Comment by kcbreuil** [comment]
Adding my additional notes here @asasmith 

* List items should be greyed out per wireframe/mockups 
* Reduce spacing between unordered List section and testing graphics — this spacing should be moved beneath the testing section

**Comment by kcbreuil** [comment]
@asasmith wireframes were updated on this to show text type. Made that edit on #36

**Comment by asasmith** [comment]
completed in #80
