### ISSUE TITLE
Add additional padding (R, L)

### ISSUE THREAD

**Issue by kcbreuil** [bckrm/silverado#23]
@asasmith see my note-- Upon loading on the Chrome browser, there is no margin around the site. Once I expanded the screen, this was rectified, but at different breakpoints it reverts to no margin. Per the wireframes I think we should add maybe a margin of 5px - 10px to just ensure it doesn’t look flushed with the site edges across browsers.

**Comment by asasmith** [comment]
@kcbreuil I was hoping that I could find a way to extend tailwind's `container` class to include padding on smaller screens. Unfortunately I haven't been able to find a solve for this.

I think the fix will be searching for instances of the `container` class in styled components and add padding util classes. Should look something like this `container px-4 md:px-0`. 

I'm going to assign this one to you, feel free to make this update once you QA is finished.

**Comment by asasmith** [comment]
Josh wants `20px` so the class will be `px-5 md:px-0`
