### ISSUE TITLE
Navigation - Mobile nav item

### ISSUE THREAD

**Issue by asasmith** [bckrm/silverado#26]
Mobile - 'What’s Happening' nav item is left aligned in navigation

**Comment by kcbreuil** [comment]
@asasmith Can I get some clarification on this one? I am not seeing what needs to be done.

**Comment by asasmith** [comment]
![Image from iOS](https://user-images.githubusercontent.com/11489171/105789023-9d3ce180-5f4f-11eb-91d3-8e63ae15c981.png)

Chrome dev tools aren't showing this but safari is if you want to confirm your fix there.

I think the problem is the nav item is too long and it's breaking on a new line. I think adding `text-align: right` on the `ul` should resolve it.
