### ISSUE TITLE
Navigation - Active Nav Item

### ISSUE THREAD

**Issue by asasmith** [bckrm/silverado#28]
“What’s happening” is underlined by default, that should only be a hover state and/or when the user is on the “What’s happening page”

@kcbreuil this is happening because the nav link is set to `/` and the active class is being applied. Update the link to `/events`

**Comment by kcbreuil** [comment]
@asasmith I had seen this, and figured it was because /events page has yet to be created. Previously the nav had two "active" nav styling but it went away when you created the about page. Should I create the /events page instead?
