### ISSUE TITLE
Address Margin-Top on All Pages

### ISSUE THREAD

**Issue by kcbreuil** [bckrm/silverado#30]

**Comment by asasmith** [comment]
Let's get guidance from Josh on this.

**Comment by kcbreuil** [comment]
@asasmith Yes, sure thing! Just moving it out of the other issue

**Comment by kcbreuil** [comment]
@asasmith I checked in with Josh about this FYI. Waiting to hear back

**Comment by kcbreuil** [comment]
@asasmith Got feedback from Josh but we both thing top margin is good now. Do you agree? If so I will move this to completed

**Comment by asasmith** [comment]
I'm happy to defer to y'alls judgement here.
