### ISSUE TITLE
Add static versions of missing animations

### ISSUE THREAD

**Issue by kcbreuil** [bckrm/silverado#32]
Homepage 

- [x] There is a large white space above How Accelerators Work. Do we want something here? Wireframe shows some type of graphic. 

Initiatives 

- [x]  Replace IMG with Bubble graphic/animation

* does this change with mobile responsiveness?

- [x] Missing three line graphic 

- [x] Mobile responsiveness calendar icon 

About 

- [x]  Image needs to be changed for illustration

Beneath image/illustraton div:
    

- [x] Vision Headline and adjoining text is missing

    

- [ ] History Graphic is missing

**Comment by asasmith** [comment]
@kcbreuil let's use this ticket to add static versions of the animations.

**Comment by kcbreuil** [comment]
@asasmith Ah thank you :)

**Comment by kcbreuil** [comment]
@asasmith aside from the history graphic this is complete. I think we can close this
