### ISSUE TITLE
Navigation - Top Headline distorted in Mobile View 

### ISSUE THREAD

**Issue by kcbreuil** [bckrm/silverado#33]

**Comment by asasmith** [comment]
@kcbreuil can you add screen shots and a description?

**Comment by kcbreuil** [comment]
<img width="200" alt="Screen Shot 2021-01-22 at 3 40 42 PM" src="https://user-images.githubusercontent.com/61708936/105543843-470a3d00-5cc8-11eb-902d-dad768ea360b.png">
 @asasmith Sure thing, when the site is in mobile view, it seems the nav and top headline become distorted. This is happening across the browser on every page below 450px

**Comment by kcbreuil** [comment]
@asasmith Can I move this to dev ready or is there another course of action you'd like to take?
