### ISSUE TITLE
About page - missing Vision headline and content Section  

### ISSUE THREAD

**Issue by kcbreuil** [bckrm/silverado#39]

**Comment by kcbreuil** [comment]
<img width="291" alt="Screen Shot 2021-01-25 at 2 14 57 PM" src="https://user-images.githubusercontent.com/61708936/105754210-ca6d9d80-5f17-11eb-8541-764a37e492cb.png">

**Comment by asasmith** [comment]
Use the `CopyWithCta` component for this section. You'll need to add a heading element (h2) and use renderProps to conditionally hide/show it based on the heading prop's existence. Same Pattern as the transition and cta.

**Comment by kcbreuil** [comment]
@asasmith hm I am moving this over to issue #35 as I made the edits there. Will fix it now

**Comment by asasmith** [comment]
Might be better to keep it in it's own branch. The work is unique enough to warrant it.

**Comment by kcbreuil** [comment]
@asasmith Just seeing this and just pushed up but I linked the PR here. Sorry about that!

**Comment by asasmith** [comment]
no worries. Let's just try to keep pr's as unique as possible moving forward.
